amp: False
gradient_clipping: 1.0
weight_decay: 1e-8
learning_rate: 1e-5
input_image_shape: 512


training_root: '/workspace/1AlgoG3/Project_Scripts/Tumor_Non_Tumor/Training'
run_name : 'Trials'
data_root: '/workspace/1AlgoG3/Project_Data/Tumor_Non_Tumor/TNT_Dataset_3Class'
